name: seaweed_scale_up_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.4.3
  - setuptools=61.2.0
  - pytest=7.1.2
  - numpy=1.23.1
  - matplotlib=3.5.1
  - scipy=1.9.3
